version: "3"
services:
  bnk-database:
    image: boolnetwork/bnk-database:latest
    network_mode: "host"
    environment:
      RUST_LOG: info
    volumes:
      - ./configs/db.toml:/bnk/db.toml
      - ./data:/bnk/data

  bnk-watcher:
    image: boolnetwork/bnk-watcher:latest
    network_mode: "host"
    environment:
        RUST_LOG: info
    volumes:
        - ./configs/watcher.toml:/bnk/watcher.toml
    depends_on:
        - bnk-database

  bnk-sgx-key-server:
    image: boolnetwork/bnk-sgx-key-server:latest
    network_mode: "host"
    environment:
        RUST_LOG: info
    volumes:
        - ./configs/key.toml:/bnk/key.toml
        - ./configs/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf
    devices:
        - /dev/sgx/enclave
        - /dev/sgx/provision
    depends_on:
        - bnk-watcher