port = 8740
database_url = "bnk/data/sqlite.db"
notified_url = "http://localhost:8750/event"

[[endpoints]]
chain_id = 5
name = "goerli"
http_url = "https://rpc.goerli.dev"
private_key = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[endpoints]]
chain_id = 80001
name = "mumbai"
http_url = "https://polygontestapi.terminet.io/rpc"
private_key = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[endpoints]]
chain_id = 420
name = "optimism"
http_url = " https://goerli.optimism.io"
private_key = "0x0000000000000000000000000000000000000000000000000000000000000000"

[[sources]]
named = "broadcaster"
tag = ""
kind = "Contract"
backend = "mumbai"
address = "0x58F7616FF46De73197C6f79049f6387954223451"

[sources.watcher]
enabled = true
polling_interval = 20000
max_step = 1000
begin_height = 29177100

[[sources]]
named = "factory"
tag = ""
kind = "Contract"
backend = "mumbai"
address = "0x4d0c3b2bb15a114C6cBfa531BdeF9050809658B5"

[sources.watcher]
enabled = true
polling_interval = 20000
max_step = 1000
begin_height = 29177100

[[sources]]
named = "broadcaster"
tag = ""
kind = "Contract"
backend = "optimism"
address = "0x97543Bb9ab8BA62Aa60F596f84792f5766dd2765"

[sources.watcher]
enabled = true
polling_interval = 20000
max_step = 1000
begin_height = 2723200

[[sources]]
named = "factory"
tag = ""
kind = "Contract"
backend = "optimism"
address = "0x120F373F6b843A49D9103593a691F07571f6B11E"

[sources.watcher]
enabled = true
polling_interval = 20000
max_step = 1000
begin_height = 2723200

[[sources]]
named = "broadcaster"
tag = ""
kind = "Contract"
backend = "goerli"
address = "0xf05467484fF502A94B7Aeb704A368B33B52c529c"

[sources.watcher]
enabled = true
polling_interval = 20000
max_step = 1000
begin_height = 7961800

[[sources]]
named = "factory"
tag = ""
kind = "Contract"
backend = "goerli"
address = "0x914FfCA8E10776a7d92305BCE2Be23B4f682Ab04"

[sources.watcher]
enabled = true
polling_interval = 20000
max_step = 1000
begin_height = 7961800

[default_watcher]
enabled = true
polling_interval = 30000
max_step = 2000
begin_height = 0