port = 18740
database_url = "/bnk/data/sqlite.db"
[[endpoints]]
chain_id = 5
name = "goerli"
http_url = "https://rpc.goerli.dev"

[[endpoints]]
chain_id = 80001
name = "mumbai"
http_url = "https://polygontestapi.terminet.io/rpc"

[[endpoints]]
chain_id = 420
name = "optimism"
http_url = " https://goerli.optimism.io"

[default_watcher]
enabled = true
polling_interval = 30000
max_step = 2000
begin_height = 0
