# local msg_pool server port.
msg_pool_port = 18720
# local node url for watcher
node_ws_url = "ws://localhost:9944"
# local database url for data storage.
db_url = "http://localhost:18710"
# local database token for database usage.
db_token = ""
# local sgx key server url
key_server_url = "https://localhost:18730"
# used to generate LocalKeyStore, used to get AccountId in substrate.
identity = "0x0000000000000000000000000000000000000000000000000000000000000000"
# seconds per block
block_time = 3
# blocks per epoch
epoch_duration = 200

[network_config]
port = 38700
boot_nodes = ["/ip4/20.3.233.7/tcp/38700/p2p/12D3KooWEZopB8nMuMGFT24LrkGzxCEkwUpY4w5mgY78biy8ZiU5"]
share_peer_interval = 30
only_global_ips = true