# local msg_pool server port.
msg_pool_port = 8720
# local node url for watcher
node_ws_url = "ws://127.0.0.1:9944"
# local database url for data storage.
db_url = "http://127.0.0.1:8710"
# local database token for database usage.
db_token = ""
# local sgx key server url
key_server_url = "https://localhost:8730"
# used to generate LocalKeyStore, used to get AccountId in substrate.
identity = "0x0000000000000000000000000000000000000000000000000000000000000000"
# Notifies relayer of the event
relayer_server_url = "http://localhost:8750"
# seconds per block
block_time = 3
# blocks per epoch
epoch_duration = 200

[network_config]
port = 38700
boot_nodes = ["/ip4/20.3.233.7/tcp/38700/p2p/12D3KooWEZopB8nMuMGFT24LrkGzxCEkwUpY4w5mgY78biy8ZiU5"]
share_peer_interval = 30
only_global_ips = true